export { default as useFetchData } from './useFetchData'
export { default as useAvgAgeData } from './useAvgAgeData'
export { default as useRunningAvgData } from './useRunningAvgData'
export { default as useRunningTotalData } from './useRunningTotalData'
export { default as useGenderRatioData } from './useGenderRatioData'